version: "3"
services:
    mongodb:
        image: mongo
        ports:
            - '27017:27017'
    redis:
        image: redis
        ports:
            - '6379:6379'
    mercury-inventory:
        image: local/mercury-core:latest
        environment:
            LOG_LEVEL: DEBUG
            INVENTORY_BIND_ADDRESS: tcp://0.0.0.0:9000
            INVENTORY_DATABASE_SERVERS: mongodb:27017
            INVENTORY_DATABASE_NAME: mercury
            INVENTORY_DATABASE_COLLECTION: inventory
            INVENTORY_DATABASE_REPLICA_NAME: ""
            ASYNCIO_DEBUG: 0
        depends_on:
            - mongodb
        ports:
            - '9000:9000'
        command: mercury-inventory
    mercury-rpc:
        image: local/mercury-core:latest
        ports:
            - '9001:9001'
        environment:
            LOG_LEVEL: DEBUG
            RPC_BIND_ADDRESS: tcp://0.0.0.0:9001
            RPC_DATABASE_SERVERS: mongodb:27017
            RPC_DATABASE_NAME: mercury
            RPC_DATABASE_REPLICA_NAME: ""
            RPC_DATABASE_JOBS_COLLECTION: rpc_jobs
            RPC_DATABASE_TASKS_COLLECTION: rpc_tasks
            ASYNCIO_DEBUG: 0
            SUBTASK_DEBUG: 0
        depends_on:
            - mongodb
        command: mercury-rpc
    mercury-backend:
        image: local/mercury-core:latest
        ports:
            - '9002:9002'
        environment:
            LOG_LEVEL: DEBUG
            BACKEND_AGENT_SERVICE_BIND_ADDRESS: tcp://0.0.0.0:9002
            ASYNCIO_DEBUG: 0
            SUBTASK_DEBUG: 0
            BACKEND_ORIGIN_NAME: docker1
            BACKEND_ORIGIN_DATACENTER: docker1
            BACKEND_ORIGIN_PUBLIC_ADDRESS: mercury-backend
            BACKEND_ORIGIN_FRONTEND_PORT: 9001
            BACKEND_INVENTORY_ROUTER: tcp://mercury-inventory:9000
            BACKEND_PING_INTERVAL: 30
            BACKEND_PING_CYCLE_TIME: 10
            BACKEND_PING_INITIAL_TIMEOUT: 2500
            BACKEND_PING_RETRIES: 5
            BACKEND_PING_BACKOFF: .42
            BACKEND_RPC_ROUTER: tcp://mercury-rcp:9001
        depends_on:
            - mercury-rpc
            - mercury-inventory
        command: mercury-backend
    mercury-backend_queue:
        image: local/mercury-core:latest
        links:
            - "redis"
            - "mercury-inventory"
        environment:
            LOG_LEVEL: DEBUG
            BACKEND_REDIS_HOST: redis
            BACKEND_REDIS_PORT: 6379
            BACKEND_REDIS_QUEUE: rpc_task_queue
            BACKEND_INVENTORY_ROUTER: tcp://mercury-inventory:9000
        command: mercury-backend-queue
    mercury-backend_worker:
        image: local/mercury-core:latest
        environment:
            LOG_LEVEL: DEBUG
            BACKEND_REDIS_HOST: redis
            BACKEND_REDIS_PORT: 6379
            BACKEND_REDIS_QUEUE: rpc_task_queue
            BACKEND_WORKERS_THREADS: 10
            BACKEND_WORKERS_MAX_REQUESTS_PER_THREAD: 1
            BACKEND_RPC_ROUTER: tcp://mercury-rpc:9001
        depends_on:
            - redis
            - mercury-rpc
        command: mercury-backend-worker
    mercury-log:
        image: local/mercury-core:latest
        ports:
            - '9006:9006'
        environment:
            LOG_LEVEL: DEBUG
            LOG_SERVICE_BIND_ADDRESS: tcp://0.0.0.0:9006
            LOG_SERVICE_DB_SERVERS: mongodb:27017
            LOG_SERVICE_DB_NAME: mercury
            LOG_SERVICE_DB_COLLECTION: log
            LOG_SERVICE_DB_REPLICA_NAME: ""
        depends_on:
            - mongodb
        command: mercury-log

